### ISSUE TITLE
Add footer with a link to the source code

### ISSUE THREAD

**Issue by Devansh-Baghel** [Devansh-Baghel/tic-tac-toe#1]
## Just make sure of that:

1. Footer should follow similar design as the rest of the website.

**Comment by ChaudaryHammad** [comment]
hi, I want to work on this issue. Assign me and kindly explain a bit more.

**Comment by Devansh-Baghel** [comment]
@ChaudaryHammad just add a footer on the main screen of the website here:

![Screenshot from 2023-09-30 23-48-23](https://github.com/Devansh-Baghel/tic-tac-toe/assets/77718741/5011610d-a580-4170-b079-4c9f999a2b8d)

The footer should have a link to this repo and say "source code".

Also the footer should have rounded border, and be the same color as the cells in tic tac toe

**Comment by ChaudaryHammad** [comment]
ok

**Comment by ChaudaryHammad** [comment]
Is this is enough? 
![image](https://github.com/Devansh-Baghel/tic-tac-toe/assets/102407219/271ac8e0-3d1a-48bb-b15d-3586c8f93c74)

**Comment by Devansh-Baghel** [comment]
Closed by #2
